# Generated by Django 5.2.8 on 2025-12-01 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('confirmation_limit_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=10, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Membro da Diretoria'), (2, 'Membro do Conselho'), (3, 'Comissão de Educação'), (4, 'Secretário Regional'), (5, 'Coordenador de Comissão Especial'), (6, 'Outros')])),
                ('individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('double', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_covered', models.IntegerField(default=0)),
            ],
        ),
    ]
