# Generated by Django 5.2.8 on 2025-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=10)),
                ('neighbourhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
