# Generated by Django 5.2.8 on 2025-12-01 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('institution', models.CharField(blank=True, max_length=80, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Membro da Diretoria'), (2, 'Membro do Conselho'), (3, 'Comissão de Educação'), (4, 'Secretário Regional'), (5, 'Coordenador de Comissão Especial'), (6, 'Outros')])),
                ('room_type', models.IntegerField(choices=[(1, 'Individual'), (2, 'Duplo'), (3, 'Com Convidado')])),
                ('people_count', models.IntegerField(default=1)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('special_needs', models.TextField(blank=True, default='')),
                ('origin_city', models.CharField(blank=True, default='', max_length=60)),
                ('origin_state', models.CharField(blank=True, default='', max_length=2)),
                ('origin_airport', models.CharField(blank=True, default='', max_length=60)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_preferred_time', models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], default=0)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_preferred_time', models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], default=0)),
                ('expected_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Aguardando Pagamento'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.event')),
            ],
        ),
    ]
