# Generated by Django 5.2.8 on 2025-12-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='departure_preferred_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_preferred_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada')], default=0),
        ),
    ]
