# Generated by Django 5.2.8 on 2025-12-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_departure_preferred_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='departure_preferred_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada')], null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='origin_airport',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='origin_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='origin_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_preferred_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada')], null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='special_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
